### ISSUE TITLE
Bugs and Issues

### ISSUE THREAD

**Issue by ralphZero** [Aperio-Haiti/Aperio#10]
*Signup vendor make sure that the address is mandatory
*review map vendor design
*map vendor (make it show other vendor but me)
*login with email (already fixed)

**Comment by ralphZero** [comment]
* review map vendor design design (fixed)
* *map vendor (make it show other vendor but me) (Modified)

**Comment by sauvelino** [comment]
debug{
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

add this in the buildType under release

**Comment by ralphZero** [comment]
ki erreur sa?

**Comment by sauvelino** [comment]
Erreur map batay depi matin an c akoz limenm

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
