### ISSUE TITLE
FrontEnd Building

### ISSUE THREAD

**Issue by ralphZero** [Aperio-Haiti/Aperio#5]
Login page
All Signup pages

**Comment by codepathreview** [comment]
Please updated your group information :
https://courses.codepath.com/courses/android_university/pages/group/02_update_group_info 
/cc @codepathreview

**Comment by cbaja** [comment]
You can close that issue too.

**Comment by ralphZero** [comment]
> You can close that issue too.

Hi Mr Baja, 
Can you please send us the document we asked you about yesterday.
